### PR TITLE
Better compat with ecto >= 2.0

### PR DESCRIPTION
**Pull request by esdras**
There is already a pull request that tries to solve this problem, but it adds ecto as a dependency and seems to be stuck.

Bumped version to 0.2.0

### CODE REVIEW

**Comment by williamgueiros** [comment]
💚 ❤️

**Comment by williamgueiros** [comment]
more 2 days i will generate hex pack, sorry delay

**Comment by williamgueiros** [comment]
the document not change ?? i don't have experience in ecto  @esdras

**Comment by esdras** [comment]
API stays the same, basically the changeset data structure changed. 
I bumped the elixir version to >= 1.4. That is what is making the CI fail, maybe change the CI script?

**Comment by williamgueiros** [comment]
now i fixed that, and add elixir 1.4, 1.8 in CI
https://travis-ci.org/williamgueiros/Brcpfcnpj/builds/497675192

**Pull request merged**
